version: "3.9"
services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    container_name: ktor-arrow-example-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ktor-arrow-example-database
